apiVersion: v1
kind: ConfigMap
data:
  mapUsers: |
    - userarn: arn:aws:iam::<AWS ACCOUNT ID>:user/github-ci
      username: github-ci
      groups:
        - system:masters
metadata:
  name: aws-auth
  namespace: kube-system
