apiVersion: apps/v1
kind: Deployment
metadata:
  name: trivial-bank-api-deployment
  labels:
    app: trivial-bank-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trivial-bank-api
  template:
    metadata:
      labels:
        app: trivial-bank-api
    spec:
      containers:
        - name: trivial-bank-api
          image: <AWS account ID>.dkr.ecr.us-east-2.amazonaws.com/trivialbank:<image ID>
          ports:
            - containerPort: 8080
