apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: trivial-bank-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: "nginx"
  rules:
    - host: api.terraverdeconsulting.com
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: trivial-bank-api-service
                port:
                  number: 80
  tls:
    - hosts:
        - api.terraverdeconsulting.com
      secretName: trivial-bank-api-cert
